### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by kortov**

### CODE REVIEW

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this pull request

**Comment by 0crat** [comment]
@kortov[/z](https://www.0crat.com/u/kortov) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Comment by g4s8** [comment]
@kortov thanks!

**Comment by 0crat** [comment]
Job `gh:g4s8/gitstrap#43` is not assigned, can't get performer

**Pull request merged**
