### PR TITLE
Template URLs

### PR DESCRIPTION
**Pull request by g4s8**
For #2 
 - support template urls
 - updated readme
 - added few simple templates to repo

### CODE REVIEW

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job [#12](https://github.com/g4s8/gitstrap/issues/12) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `REV` is banned at [#12](https://github.com/g4s8/gitstrap/issues/12); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Job `gh:g4s8/gitstrap#12` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#12](https://github.com/g4s8/gitstrap/issues/12) is now out of scope

**Pull request merged**
