### PR TITLE
Repo name from pwd if config is empty

### PR DESCRIPTION
**Pull request by g4s8**
#14 - repo name from pwd if config is empty

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#16](https://github.com/g4s8/gitstrap/issues/16) is now in scope, role is `REV`

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `REV` is banned at [#16](https://github.com/g4s8/gitstrap/issues/16); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:g4s8/gitstrap#16` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#16](https://github.com/g4s8/gitstrap/issues/16) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Pull request merged**
